# Generated by Django 6.1 on 2026-08-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exception_dates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
