# Generated by Django 3.2.25 on 2026-08-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20260806_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='#039be5', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='recurring_rule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
