# Generated by Django 6.1 on 2026-08-06 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_auto_20260806_1630'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendar',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_calendars', to=settings.AUTH_USER_MODEL),
        ),
    ]
