# Generated by Django 6.1 on 2026-08-06 19:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_calendar_is_public_calendar_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
