# Generated by Django 6.1 on 2026-08-06 19:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_calendar_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
